"""Setup basic tables

Revision ID: 048c32749d9c
Revises:
Create Date: 2025-03-18 23:39:01.880759

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "048c32749d9c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poem",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("num_segments", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "segment",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("poem_uid", sa.String(), nullable=False),
        sa.Column("previous_segment_uid", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segment")
    op.drop_table("poem")
    # ### end Alembic commands ###
